# Generated by Django 4.1.2 on 2022-10-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
