# Generated by Django 4.1.2 on 2022-11-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_extended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BR', 'Borrow'), ('RT', 'Return'), ('EX', 'Extend'), ('TW', 'Time Warning'), ('GN', 'General'), ('AV', 'Available'), ('CM', 'Comment')], default='GN', max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BR', 'امانت'), ('RT', 'بازگشت'), ('EX', 'تمدید'), ('CM', 'کامنت')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=None, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestBook', to='books.book')),
            ],
        ),
    ]
